name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Init and Test
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\test.ps1

  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Init and Test
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\test.ps1

  format:
    name: PowerShell2
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Init
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\scoop_core\test\bin\init.ps1
          .\my_bucket\bin\formatjson.ps1

      
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          path: my_bucket
          author: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          branch: formatjson
          base: ${{ github.head_ref }}
          delete-branch: true
          title: 'Format json'
          commit-message: 'Format json'
          committer: 'GitHub <noreply@github.com>'
          body: |
            Format json.
